version: '3'
services:
  app:
    build: .
    container_name: redache_app
    volumes:
      - .:/app/
    links:
      - redis

  redis:
    image: redis
    container_name: redache_redis
    ports:
      - 6379
